GET http://localhost:3003/ping
###

GET http://localhost:3003/users
###

GET http://localhost:3003/products
###

GET http://localhost:3003/purchase/pur001
###

POST http://localhost:3003/users
Content-Type: application/json

{
    "id": "u009",
    "name": "9Astrodev9",
    "email": "9astrodev9@email.com",
    "password": "astro9999",
    "createdAt": "17/10/2023"
}
###

POST  http://localhost:3003/products
Content-Type: application/json

{
    "id": "prod002",
    "name": "Cadeira gamer",
    "price": 2000,
    "description": "Cadeira confortavel para gamer",
    "imageUrl": "https://picsum.photos/seed/Teclado%20gamer/400"
}
###

POST http://localhost:3003/purchases
Content-Type: application/json

{
     "id": "pur002",
    "buyer": "u003",
    "products": [
        {
            "id": "p005",
            "quantity": 2
        },
        {
            "id": "p006",
            "quantity": 3
        }
    ]
}
###

PUT http://localhost:3003/products/p0022
Content-Type: application/json

{
    "id": "prod0033",
    "name": "Teclado gamer RGB",
    "price": 300,
    "description": "Teclado mecânico com RGB e numpad",
    "imageUrl": "https://picsum.photos/seed/Teclado%20gamer%20RGB/400"
}
###
DELETE http://localhost:3003/purchases/pur001
###